name: Update packagist dev-main
on:
  push:
    branches: [ main ]
jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  release:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v2.3.4

      # Setup PHP environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      # Install Composer
      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          php -r "unlink('composer-setup.php');"

      # Install dependencies (required by Run tests step)
      - name: Install dependencies
        run: composer install

      # Publish version to Packagist
      - name: Publish
        run: composer config --global github-oauth.github.com ${{ secrets.GITHUB_TOKEN }} && composer update --no-scripts