name: Update packagist dev-main
on:
  push:
    branches: [ main ]
jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  release:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      # Publish version to Packagist
      - name: Publish
        run: composer config --global github-oauth.github.com ${{ secrets.GITHUB_TOKEN }} && composer update --no-scripts