name: Release package
on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Release tag: enter the tag name for the release'
        required: true
jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  release:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v2.3.4

      # Setup PHP environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      # Install Composer
      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          php -r "unlink('composer-setup.php');"

      # Install dependencies (required by Run tests step)
      - name: Install dependencies
        run: composer install

      # Configure Git
      - name: Git configuration
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      # Update changelog unreleased section with new version
      - name: Update changelog
        uses: superfaceai/release-changelog-action@v1
        with:
          path-to-changelog: CHANGELOG.md
          version: ${{ github.event.inputs.release-tag }}
          operation: release

      # Commit changes
      - name: Commit CHANGELOG.md and composer.json changes and create tag
        run: |
          git add "composer.json"
          git add "CHANGELOG.md"
          git commit -m "chore: release ${{ github.event.inputs.release-tag }}"
          git tag ${{ github.event.inputs.release-tag }}

      # Push repository changes
      - name: Push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin && git push --tags

      # Publish version to Packagist
      - name: Publish
        run: composer config --global github-oauth.github.com ${{ secrets.GITHUB_TOKEN }} && composer update --no-scripts

      # Read version changelog
      - id: get-changelog
        name: Get version changelog
        uses: superfaceai/release-changelog-action@v1
        with:
          path-to-changelog: CHANGELOG.md
          version: ${{ github.event.inputs.release-tag }}
          operation: read

      # Update GitHub release with changelog
      - name: Update GitHub release documentation
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release-tag }}
          body: ${{ steps.get-changelog.outputs.changelog }}
          prerelease: ${{ endsWith(github.event.inputs.release-tag, 'alpha') || endsWith(github.event.inputs.release-tag, 'beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
