name: Test on Push
on: [workflow_call]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v2.3.4

      # Setup PHP environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      # Install Composer
      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          php -r "unlink('composer-setup.php');"

      # Install dependencies
      - name: Install dependencies
        run: composer install

      # Composer analysis
      - name: Composer analyse
        run: composer analyse

      # Composer linting
      - name: Composer lint
        run: composer lint

      # Run tests
      - name: Run tests
        run: composer test
